# Generated by Django 5.2.4 on 2025-07-31 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mylogin', '0002_remove_customuser_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
