# Generated by Django 5.2.4 on 2025-08-28 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylogin', '0003_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_slip',
            field=models.ImageField(blank=True, help_text='แนบสลิปการชำระเงิน', null=True, upload_to='payment_slips/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='เลขบัญชี'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ชื่อธนาคาร'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'รออนุมัติ'), ('approved', 'รอชำระเงิน'), ('awaiting_confirmation', 'รอเจ้าของยืนยัน'), ('completed', 'เสร็จสิ้น'), ('rejected', 'ถูกปฏิเสธ'), ('cancelled', 'ยกเลิกแล้ว')], default='pending', max_length=30),
        ),
    ]
