# Generated by Django 5.2.4 on 2025-08-29 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mylogin', '0004_booking_payment_slip_customuser_bank_account_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='bank_account_number',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='bank_name',
        ),
    ]
