# Generated by Django 5.2.4 on 2025-08-29 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylogin', '0005_remove_customuser_bank_account_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='เลขบัญชี'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ชื่อธนาคาร'),
        ),
    ]
