# Generated by Django 5.2.4 on 2025-08-29 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylogin', '0006_customuser_bank_account_number_customuser_bank_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='เลขบัญชี'),
        ),
    ]
