# Generated by Django 5.2.4 on 2025-08-03 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylogin', '0006_alter_customuser_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_num',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
    ]
