# Generated by Django 5.2.4 on 2025-08-11 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylogin', '0007_alter_customuser_phone_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('venue_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('price_per_day', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('extra_amenities', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='VenueAmenity',
            fields=[
                ('venue', models.OneToOneField(db_column='venue_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='mylogin.venue')),
                ('wifi', models.BooleanField(default=False)),
                ('parking', models.BooleanField(default=False)),
                ('equipment', models.BooleanField(default=False)),
                ('sound_system', models.BooleanField(default=False)),
                ('projector', models.BooleanField(default=False)),
                ('air_conditioning', models.BooleanField(default=False)),
                ('seating', models.BooleanField(default=False)),
                ('drinking_water', models.BooleanField(default=False)),
                ('first_aid', models.BooleanField(default=False)),
                ('cctv', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='VenueImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='venue_images/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('venue', models.ForeignKey(db_column='venue_id', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='mylogin.venue')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
