# Generated by Django 5.2.4 on 2025-08-12 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylogin', '0008_venue_venueamenity_venueimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venueimage',
            name='order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
