# Generated by Django 5.2.4 on 2025-08-12 17:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylogin', '0009_alter_venueimage_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='owner',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='venues', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
