# Generated by Django 5.2.4 on 2025-09-24 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylogin', '0009_venue_code_venue_latitude_venue_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='code',
            field=models.CharField(blank=True, default=0, max_length=32),
            preserve_default=False,
        ),
    ]
