# Generated by Django 5.2.7 on 2025-11-01 14:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylogin', '0011_activity'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityParticipants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('joined', 'เข้าร่วมแล้ว'), ('checked_in', 'ลงทะเบียนแล้ว'), ('cancelled', 'ยกเลิก')], default='joined', max_length=20)),
                ('activity', models.ForeignKey(db_column='activity_id', on_delete=django.db.models.deletion.CASCADE, to='mylogin.activity')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Activity Participants',
                'unique_together': {('activity', 'user')},
            },
        ),
    ]
