# Generated by Django 5.2.7 on 2025-11-02 15:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylogin', '0012_activityparticipants'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='joined_activities', through='mylogin.ActivityParticipants', to=settings.AUTH_USER_MODEL),
        ),
    ]
