# Generated by Django 5.2.7 on 2025-11-03 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mylogin', '0013_activity_participants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='location',
        ),
    ]
