# Generated by Django 5.2.7 on 2025-11-13 18:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylogin', '0014_remove_activity_location'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activityparticipants',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='activityparticipants',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='activityparticipants',
            name='is_manual',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='activityparticipants',
            name='manual_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='activityparticipants',
            name='manual_full_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='activityparticipants',
            name='manual_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='activityparticipants',
            name='manual_phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='activityparticipants',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_participations', to='mylogin.activity'),
        ),
        migrations.AlterField(
            model_name='activityparticipants',
            name='status',
            field=models.CharField(choices=[('joined', 'เข้าร่วม'), ('cancelled', 'ยกเลิก')], default='joined', max_length=20),
        ),
        migrations.AlterField(
            model_name='activityparticipants',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_participations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='activityparticipants',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('activity', 'user'), name='unique_activity_user_participation'),
        ),
    ]
