# Generated by Django 5.2.7 on 2025-11-17 18:34

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylogin', '0016_alter_customuser_dob'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['-start_date', '-start_time']},
        ),
        migrations.AlterModelOptions(
            name='activityparticipants',
            options={'ordering': ['activity', '-joined_at']},
        ),
        migrations.RemoveField(
            model_name='activity',
            name='date',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='time',
        ),
        migrations.AddField(
            model_name='activity',
            name='end_date',
            field=models.DateField(blank=True, help_text='วันที่จบกิจกรรม (เว้นว่างได้ ถ้าจัดวันเดียว)', null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='end_time',
            field=models.TimeField(blank=True, help_text='เวลาจบกิจกรรม (เว้นว่างได้ ถ้าไม่กำหนดชัดเจน)', null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='max_participants',
            field=models.PositiveIntegerField(blank=True, help_text='จำนวนผู้เข้าร่วมสูงสุด (เว้นว่าง = ไม่จำกัด)', null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='วันที่เริ่มกิจกรรม'),
        ),
        migrations.AddField(
            model_name='activity',
            name='start_time',
            field=models.TimeField(default=datetime.time(9, 0), help_text='เวลาเริ่มกิจกรรม'),
        ),
        migrations.AddField(
            model_name='activity',
            name='status',
            field=models.CharField(choices=[('draft', 'ร่าง (ยังไม่เปิดให้ลงทะเบียน)'), ('published', 'เปิดให้ลงทะเบียน'), ('closed', 'ปิดรับลงทะเบียน'), ('cancelled', 'ยกเลิกกิจกรรม'), ('finished', 'จบกิจกรรมแล้ว')], default='published', max_length=20),
        ),
        migrations.AddField(
            model_name='activityparticipants',
            name='attended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='activityparticipants',
            name='attended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activityparticipants',
            name='is_manual',
            field=models.BooleanField(default=False, help_text='True = ลงทะเบียนแบบกรอกข้อมูลมือ (guest); False = ผูกกับ user จริง'),
        ),
        migrations.AlterField(
            model_name='activityparticipants',
            name='manual_full_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
