# Generated by Django 5.2.7 on 2025-12-11 17:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylogin', '0018_chatthread_chatmessage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1 - แย่มาก'), (2, '2 - พอใช้'), (3, '3 - ปานกลาง'), (4, '4 - ดี'), (5, '5 - ดีมาก')])),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='mylogin.venue')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('venue', 'user')},
            },
        ),
    ]
